language: node_js
node_js:
  - "0.11"
before_install: npm install -g grunt-cli bower && bower install
after_script: cat ./coverage/PhantomJS\ 1.9.7\ \(Linux\)/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage